# Copied and modified from https://github.com/digital-earths-global-hackathon/tools/blob/main/python_envs/environment.yaml
channels:
- conda-forge
- nodefaults
dependencies:
- python==3.12.*
- aiohttp
- cartopy
- cdsapi
- cfgrib
- cfunits
- cmocean
- dask
- dask-jobqueue
- distributed
- easygems
- fastparquet
- flox
- h5netcdf
- hdf5plugin
- healpix
- healpy
- hvplot
- intake==0.7.0
- intake-esm
- intake-stac
- intake-xarray==0.7.0
- ipykernel
- iris
- jupyter
- jupyterlab
- jupytext
- libnetcdf>=4.9.2
- matplotlib
- metpy
- netcdf4
- numba
- numpy
- odc-stac
- opencv
- pandas
- polars
- pyflextrkr
- pystac
- pytest
- requests
- rioxarray
- ruff
- s3fs
- scipy
- seaborn
- sh
- spectrum
- tobac
- tokenizers
- tqdm
- types-pyyaml
- uxarray
- xarray
- xdggs
- xgcm
- zarr<3.0.0
- pip
- pip:
  - gribscan

name: llj